### PR TITLE
Added darknet inference engine with cudnn

### PR DESCRIPTION
**Pull request by Nuzhny007**
1. Changed relative path to the models
2. Added darknet inference engine with cudnn from this fork: https://github.com/AlexeyAB/darknet
It was tested only on Windows 10 laptop with GF 1060, driver version 417.35, CUDA version 10.0, cudnn version cudnn-10.0-windows10-x64-v7.3.0.29

For using darknet inference it need set in CMake option BUILD_YOLO_LIB=ON and run MultitargetTracker.exe ../../data/atrium.avi -e=6 -g=0

3. Fixed compilation bug with OpenCV 3.4

### CODE REVIEW

**Comment by iraadit** [comment]
I'm unable to compile Darknet part on Linux

Code is running alright if I compile Darknet by myself and put the .so file where needed though.

Thanks !

> -- Found CUDA: /usr/local/cuda-9.1 (found version "9.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fnlocal/codes/OBJECT_DETECTION/Multitarget-tracker
[  1%] Building NVCC (Device) object src/Detector/darknet/CMakeFiles/yolo_lib.dir/yolo_lib_generated_activation_kernels.cu.o
/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h(436): error: identifier "nullptr" is undefined
/usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h(436): error: expected a ";"
/usr/include/x86_64-linux-gnu/c++/5/bits/c++config.h(200): error: expected a ";"
/usr/include/c++/5/exception(63): error: expected a ";"
/usr/include/c++/5/exception(68): error: expected a ";"
/usr/include/c++/5/exception(76): error: expected a ";"
/usr/include/c++/5/exception(83): error: expected a ";"
/usr/include/c++/5/exception(93): error: expected a "{"
/usr/include/c++/5/bits/exception_ptr.h(64): error: function "std::current_exception" returns incomplete type "std::__exception_ptr::exception_ptr"
/usr/include/c++/5/bits/exception_ptr.h(64): error: expected a "{"
/usr/include/c++/5/bits/exception_ptr.h(79): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(81): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(82): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(84): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(86): error: declaration is incompatible with previous "std::current_exception"
(64): here
/usr/include/c++/5/bits/exception_ptr.h(86): error: use of a local type to declare a function
/usr/include/c++/5/bits/exception_ptr.h(86): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(87): error: use of a local type to declare a function
/usr/include/c++/5/bits/exception_ptr.h(90): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(92): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(95): error: incomplete type is not allowed
/usr/include/c++/5/bits/exception_ptr.h(95): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(116): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(126): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(143): error: use of a local type to declare a function
/usr/include/c++/5/bits/exception_ptr.h(144): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(147): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(152): error: use of a local type to declare a function
/usr/include/c++/5/bits/exception_ptr.h(153): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(156): error: use of a local type to declare a function
/usr/include/c++/5/bits/exception_ptr.h(157): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(160): error: use of a local type to declare a function
/usr/include/c++/5/bits/exception_ptr.h(161): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(169): error: expected a ";"
/usr/include/c++/5/bits/exception_ptr.h(195): error: expected a ";"
/usr/include/c++/5/bits/nested_exception.h(57): error: incomplete type is not allowed
/usr/include/c++/5/bits/nested_exception.h(60): error: expected a ";"
/usr/include/c++/5/bits/nested_exception.h(64): error: expected a ";"
/usr/include/c++/5/bits/nested_exception.h(66): error: expected a ";"
/usr/include/c++/5/bits/nested_exception.h(78): error: expected a ";"
/usr/include/c++/5/bits/nested_exception.h(73): error: identifier "rethrow_exception" is undefined
/usr/include/c++/5/bits/nested_exception.h(74): error: namespace "std" has no member "terminate"
/usr/include/c++/5/new(96): error: expected a "{"
/usr/include/c++/5/new(111): error: allocation operator may not be declared in a namespace
/usr/include/c++/5/new(113): error: allocation operator may not be declared in a namespace
/usr/include/c++/5/new(115): error: deallocation operator may not be declared in a namespace
/usr/include/c++/5/new(115): error: expected a "{"
/usr/include/c++/5/new(130): error: identifier "__p" is undefined
/usr/include/c++/5/new(131): error: allocation operator may not be declared in a namespace
/usr/include/c++/5/new(131): error: expected a "{"
/usr/include/c++/5/new(135): error: deallocation operator may not be declared in a namespace
/usr/include/c++/5/new(135): error: expected a "{"
/usr/include/c++/5/new(136): error: deallocation operator may not be declared in a namespace
/usr/include/c++/5/new(136): error: expected a "{"
/usr/include/c++/5/bits/cpp_type_traits.h(185): error: identifier "char16_t" is undefined
/usr/include/c++/5/bits/cpp_type_traits.h(192): error: identifier "char32_t" is undefined
/usr/include/c++/5/bits/cpp_type_traits.h(192): error: class "std::__is_integer<<error-type>>" has already been defined
/usr/include/c++/5/bits/cpp_type_traits.h(344): error: namespace "std::__gnu_cxx" has no member "__normal_iterator"
/usr/include/c++/5/bits/cpp_type_traits.h(344): error: expected a ">"
/usr/include/c++/5/ext/type_traits.h(159): error: inline specifier allowed on function declarations only
/usr/include/c++/5/ext/type_traits.h(160): error: declaration is incompatible with overloaded function "__gnu_cxx::__is_null_pointer"
(150): here
/usr/include/c++/5/ext/type_traits.h(160): error: namespace "std" has no member "nullptr_t"
/usr/include/c++/5/ext/type_traits.h(161): error: expected a ";"
/usr/include/c++/5/ext/type_traits.h(173): error: a template argument list is not allowed in a declaration of a primary template
/usr/include/c++/5/ext/type_traits.h(177): error: __promote is not a template
/usr/include/c++/5/ext/type_traits.h(181): error: __promote is not a template
/usr/include/c++/5/ext/type_traits.h(185): error: __promote is not a template
/usr/include/c++/5/ext/type_traits.h(189): error: __promote is not a template
/usr/include/c++/5/ext/type_traits.h(189): error: expected a ">"
/usr/include/c++/5/ext/type_traits.h(189): error: the global scope has no "__type"
/usr/include/c++/5/ext/type_traits.h(197): error: __promote is not a template
/usr/include/c++/5/ext/type_traits.h(197): error: expected a ">"
/usr/include/c++/5/ext/type_traits.h(197): error: the global scope has no "__type"
/usr/include/c++/5/ext/type_traits.h(206): error: __promote is not a template
/usr/include/c++/5/ext/type_traits.h(206): error: expected a ">"
/usr/include/c++/5/ext/type_traits.h(206): error: the global scope has no "__type"
/usr/include/c++/5/cmath(80): error: inline specifier allowed on function declarations only
/usr/include/c++/5/cmath(80): error: expected a ";"
/usr/include/c++/5/cmath(105): error: inline specifier allowed on function declarations only
/usr/include/c++/5/cmath(105): error: variable "std::constexpr" has already been defined
/usr/include/c++/5/cmath(105): error: expected a ";"
/usr/include/c++/5/cmath(124): error: inline specifier allowed on function declarations only
/usr/include/c++/5/cmath(124): error: variable "std::constexpr" has already been defined
/usr/include/c++/5/cmath(124): error: expected a ";"
/usr/include/c++/5/cmath(143): error: inline specifier allowed on function declarations only
/usr/include/c++/5/cmath(143): error: variable "std::constexpr" has already been defined
/usr/include/c++/5/cmath(143): error: expected a ";"
/usr/include/c++/5/cmath(162): error: inline specifier allowed on function declarations only
/usr/include/c++/5/cmath(162): error: variable "std::constexpr" has already been defined
/usr/include/c++/5/cmath(162): error: expected a ";"
/usr/include/c++/5/cmath(183): error: inline specifier allowed on function declarations only
/usr/include/c++/5/cmath(183): error: variable "std::constexpr" has already been defined
/usr/include/c++/5/cmath(183): error: expected a ";"
/usr/include/c++/5/cmath(202): error: inline specifier allowed on function declarations only
/usr/include/c++/5/cmath(202): error: variable "std::constexpr" has already been defined
/usr/include/c++/5/cmath(202): error: expected a ";"
/usr/include/c++/5/cmath(221): error: inline specifier allowed on function declarations only
/usr/include/c++/5/cmath(221): error: variable "std::constexpr" has already been defined
/usr/include/c++/5/cmath(221): error: expected a ";"
/usr/include/c++/5/cmath(240): error: inline specifier allowed on function declarations only
Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_000011d2_00000000-6_activation_kernels.cpp1.ii".
Compilation terminated.
CMake Error at yolo_lib_generated_activation_kernels.cu.o.cmake:266 (message):
  Error generating file
  Multitarget-tracker/src/Detector/darknet/CMakeFiles/yolo_lib.dir//./yolo_lib_generated_activation_kernels.cu.o
src/Detector/darknet/CMakeFiles/yolo_lib.dir/build.make:1342: recipe for target 'src/Detector/darknet/CMakeFiles/yolo_lib.dir/yolo_lib_generated_activation_kernels.cu.o' failed
make[2]: *** [src/Detector/darknet/CMakeFiles/yolo_lib.dir/yolo_lib_generated_activation_kernels.cu.o] Error 1
CMakeFiles/Makefile2:141: recipe for target 'src/Detector/darknet/CMakeFiles/yolo_lib.dir/all' failed
make[1]: *** [src/Detector/darknet/CMakeFiles/yolo_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Nuzhny007** [comment]
Fixed: https://github.com/Nuzhny007/Multitarget-tracker/commit/c72f41a096f087224d5a23ac6e735dff5b66f6fa

**Comment by iraadit** [comment]
That want further, but now I get:

> In file included from /Multitarget-tracker/src/Detector/darknet/utils.c:12:0:
./unistd.h:10:16: fatal error: io.h: No such file or directory
compilation terminated.
src/Detector/darknet/CMakeFiles/yolo_lib.dir/build.make:2621: recipe for target 'src/Detector/darknet/CMakeFiles/yolo_lib.dir/utils.c.o' failed
make[2]: *** [src/Detector/darknet/CMakeFiles/yolo_lib.dir/utils.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:141: recipe for target 'src/Detector/darknet/CMakeFiles/yolo_lib.dir/all' failed
make[1]: *** [src/Detector/darknet/CMakeFiles/yolo_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Nuzhny007** [comment]
Hm. The right unistd.h is here: /usr/include/unistd.h
Do you have it? The unistd.h from darkned needs only for Windows.

**Comment by iraadit** [comment]
Yes, I have it.
I'm usually able to compile Darknet without any problem (using the Makefile, not cmake like here).

**Comment by Nuzhny007** [comment]
And one more attempt: https://github.com/Smorodov/Multitarget-tracker/pull/117/commits/63fef890722d9d7631aa19e15ae02a1213395e41
Hope that works. It is strange that I have compiled.

**Comment by iraadit** [comment]
I'm sorry, the last change wasn't necessary, I didn't correctly clean my build directory after updating the code.
It's building correctly.

Thank you !

**Comment by Nuzhny007** [comment]
Fine!

**Pull request merged**
